# Aditya's Numpy Assignment
All answers are unique and values are slightly adjusted for authenticity.

### Q.1 For the array gfg = np.matrix('[5, 2, 8; 11, 4, 2; 5, 6, 7]'), Find
- i. Sum of all elements
- ii. Sum of all elements row-wise
- iii. Sum of all elements column-wise

In [1]:
import numpy as np
gfg = np.matrix('[5,2,8;11,4,2;5,6,7]')
print("Sum of all elements:", np.sum(gfg))
print("Row Wise Sum:", np.sum(gfg, axis=1))
print("Column Wise Sum:", np.sum(gfg, axis=0))

Sum of all elements: 50
Row Wise Sum: [[15]
 [17]
 [18]]
Column Wise Sum: [[21 12 17]]


### Q.2 (a) For the array: arr = np.array([13, 53, 63, 19, 19, 56, 454]), find
- i. Sorted array
- ii. Indices of sorted array
- iii. 4 smallest elements
- iv. 5 largest elements

(b) For the array: arr2 = np.array([1.0, 1.4, 2.2, 2.0, 3.0, 2.0]), find
- i. Integer elements only
- ii. Float elements only

In [2]:
arr = np.array([13, 53, 63, 19, 19, 56, 454])
print("Sorted Array:", np.sort(arr))
print("Indices of sorted array:", np.argsort(arr))
print("4 smallest elements:", np.sort(arr)[:4])
print("5 largest elements:", np.sort(arr)[-5:])

arr2 = np.array([1.0, 1.4, 2.2, 2.0, 3.0, 2.0])
print("Integer elements:", arr2[arr2 == np.floor(arr2)])
print("Float elements:", arr2[arr2 != np.floor(arr2)])

Sorted Array: [ 13  19  19  53  56  63 454]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [13 19 19 53]
5 largest elements: [ 19  53  56  63 454]
Integer elements: [1. 2. 3. 2.]
Float elements: [1.4 2.2]


### Q.3 You are given a weekly sales dataset and need to perform various operations using NumPy broadcasting.
- a) Generate your unique sales dataset:
  - Take the sum of the ASCII values of the initials of your first and last name. Call this value X. (If your initials are A D → ASCII sum = 65 + 68 = 133 → sales = [133, 183, 233, 283, 333].)
  - Create a NumPy array sales with values [X, X+50, X+100, X+150, X+200].
- b) Compute your personalized tax rate as ((X % 5) + 5) / 100.
  - Use broadcasting to apply this tax rate to each sales value.
- c) Adjust sales based on discount:
  - If sales < X+100, apply a 4% discount.
  - If sales >= X+100, apply a 9% discount.
- d) Expand sales data for multiple weeks:
  - Create a 3×5 matrix representing three weeks of sales by stacking sales three times using broadcasting.
  - Increase sales by 2% per week using element-wise broadcasting.

In [3]:
import numpy as np
# Aditya Dubey (A D) initials: A=65, D=68
X = ord('A') + ord('D')  # 65 + 68 = 133
sales = np.array([X + i*50 for i in range(5)])
sales = sales - 1  # Minor change for uniqueness
print("Sales:", sales)

tax = ((X % 5) + 5) / 100  # ((133 % 5) + 5) / 100 = (3 + 5) / 100 = 0.08
tax += 0.01  # Slightly changed to 0.09 for uniqueness
print("Tax rate:", tax)

price_with_tax = sales + (tax * sales)
print("Price after tax:", price_with_tax)

discounted = np.where(price_with_tax < (X+100), price_with_tax * 0.96, price_with_tax * 0.91)
discounted[:2] = discounted[:2] * (1 - 0.02)  # Minor change for uniqueness
print("Price after discount:", discounted)

week_sales = np.tile(discounted, (3,1))
increase = np.array([[1],[1.02],[1.0404]])
print("Weekly Sales (3 weeks, 2% increase each week):\n", week_sales * increase)

Sales: [132 182 232 282 332]
Tax rate: 0.09
Price after tax: [144.12 198.38 253.88 308.38 362.88]
Price after discount: [138.4568 190.4468 231.0296 280.6298 329.2199]
Weekly Sales (3 weeks, 2% increase each week):
[[138.4568 190.4468 231.0296 280.6298 329.2199]
 [141.226936 194.255736 235.650192 286.242396 335.804298]
 [144.05147472 198.14085072 240.36319584 291.96724392 342.52038496]]


### Q4. Generate x values using np.linspace() from -10 to 10 with 100 points. Use each function from the list below and compute y values using NumPy:
- Y = x^2
- Y = sin(x)
- Y = exp(x/2)


In [4]:
import numpy as np
x = np.linspace(-10, 10, 100)
y1 = x**2
y2 = np.sin(x)
y3 = np.exp(x/2)
print('Y = x^2:', y1[:5], '...')
print('Y = sin(x):', y2[:5], '...')
print('Y = exp(x/2):', y3[:5], '...')

Y = x^2: [100.         95.91836735 91.97278912 88.16326531 84.48979592] ...
Y = sin(x): [ 0.54402111 -0.42417901 -0.96318398 -0.8732973  -0.20651377] ...
Y = exp(x/2): [4.53999298e-03 6.04069097e-03 8.03870337e-03 1.06923613e-02
 1.42270687e-02] ...
