Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
a) Addition of 2 in all the elements  
b) Multiply 3 with all the elements 
c) Divide every element by 2 

In [1]:
import numpy as np
a = np.array([14, 25, 36, 47, 58])
print('Array + 2 : ', a + 2)
print('Array * 3 : ', a * 3)
print('Array / 2 : ', a / 2)

Array + 2 :  [16 27 38 49 60]
Array * 3 :  [ 42  75 108 141 174]
Array / 2 :  [ 7.  12.5 18.  23.5 29. ]


Q.2 Questions on Basic NumPy Array: 
a) Reverse the NumPy array: arr = np.array([2, 3, 4, 8, 5, 6]) 
b) Find the most frequent value and their indice(s) in the following arrays: 
i. x = np.array([2,3,4,5,6,2,3,2,2,2]) 
ii. y = np.array([2, 2, 2, 3, 4, 5, 3, 5, 4, 4])

In [2]:
import numpy as np
arr = np.array([2, 3, 4, 8, 5, 6])
rev = arr[::-1]
print('Reversed:', rev)

x = np.array([2,3,4,5,6,2,3,2,2,2])
y = np.array([2,2,2,3,4,5,3,5,4,4])

max_x = np.bincount(x).argmax()
max_y = np.bincount(y).argmax()

indices_x = np.where(x == max_x)[0]
indices_y = np.where(y == max_y)[0]
print('In X:')
print('Most Frequent: ', max_x)
print('Indices: ', indices_x)
print()
print('In Y:')
print('Most Frequent: ', max_y)
print('Indices: ', indices_y)

Reversed: [6 5 8 4 3 2]
In X:
Most Frequent:  2
Indices:  [0 5 7 8 9]

In Y:
Most Frequent:  2
Indices:  [0 1 2]


Q.3 For the given 2-D array arr=np.array([[15, 25, 35], [45, 55, 65], [75, 85, 95]]), access elements using row and column indices as follows: 
a) Access 1st row, 2nd column  
b) Access 3rd row, 1st column

In [3]:
import numpy as np
arr = np.array([[15, 25, 35],
               [45, 55, 65],
               [75, 85, 95]])
print(arr[0][1])
print(arr[2][0])

25
75


Q.4 Write program to create an 1-D NumPy array named aditya_array with evenly spaced 25 numbers from 12 to 102 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute? 

In [4]:
import numpy as np
aditya_array = np.linspace(12, 102, 25)
print('Array:', aditya_array)
print('Dimension: ', aditya_array.ndim)
print('Shape :', aditya_array.shape)
print('Number of elements:', aditya_array.size)
print('Data Type:', aditya_array.dtype)
print('Total bytes: ', aditya_array.nbytes)
aditya_array_reshaped = aditya_array.reshape(25, 1)
print('Using reshape:')
print(aditya_array_reshaped)
print('Using T:')
print(aditya_array.T)
print('T attribute does not transpose 1D arrays')

Array: [ 12.   15.75 19.5  23.25 27.   30.75 34.5  38.25 42.   45.75 49.5  53.25 57.  60.75 64.5  68.25 72.  75.75 79.5  83.25 87.  90.75 94.5  98.25 102.  ]
Dimension:  1
Shape : (25,)
Number of elements: 25
Data Type: float64
Total bytes:  200
Using reshape:
[[ 12.  ]
 [ 15.75]
 [ 19.5 ]
 [ 23.25]
 [ 27.  ]
 [ 30.75]
 [ 34.5 ]
 [ 38.25]
 [ 42.  ]
 [ 45.75]
 [ 49.5 ]
 [ 53.25]
 [ 57.  ]
 [ 60.75]
 [ 64.5 ]
 [ 68.25]
 [ 72.  ]
 [ 75.75]
 [ 79.5 ]
 [ 83.25]
 [ 87.  ]
 [ 90.75]
 [ 94.5 ]
 [ 98.25]
 [102.  ]]
Using T:
[ 12.    15.75  19.5   23.25  27.    30.75  34.5   38.25  42.    45.75
  49.5   53.25  57.    60.75  64.5   68.25  72.    75.75  79.5   83.25
  87.    90.75  94.5   98.25 102.  ]
T attribute does not transpose 1D arrays


Q5. Create a 2-D Array of three rows and four columns, named ucs420_aditya with following values – 12, 22, 32, 42, 52, 62, 72, 82, 92, 17, 22, 37. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ucs420_aditya. Resize the array to two rows and three columns and name it as resized_ucs420_aditya.

In [5]:
import numpy as np
ucs420_aditya = np.array([[12,22,32,42],[52,62,72,82],[92,17,22,37]])
print(ucs420_aditya)
print('Mean : ', np.mean(ucs420_aditya))
print('Median : ', np.median(ucs420_aditya))
print('Max : ', np.max(ucs420_aditya))
print('Min : ', np.min(ucs420_aditya))
print('Unique elements: ', np.unique(ucs420_aditya))
print()
reshaped_ucs420_aditya = ucs420_aditya.reshape(4,3)
print('Reshaped:')
print(reshaped_ucs420_aditya)
print()
resized_ucs420_aditya = np.resize(ucs420_aditya, (2,3))
print('Resized:')
print(resized_ucs420_aditya)

[[12 22 32 42]
 [52 62 72 82]
 [92 17 22 37]]
Mean :  46.5
Median :  37.0
Max :  92
Min :  12
Unique elements:  [12 17 22 32 37 42 52 62 72 82 92]

Reshaped:
[[12 22 32]
 [42 52 62]
 [72 82 92]
 [17 22 37]]

Resized:
[[12 22 32]
 [42 52 62]]
