<a href="https://colab.research.google.com/github/aditya-username/cognitive-computing/blob/main/cc_ass7_aditya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

QUE 1: Part-I

In [1]:
# Importing required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Setting a different random seed for reproducibility
np.random.seed(123456789)

In [3]:
# Generating random sales data for 12 months and 4 categories
sales_data = np.random.randint(1000, 5001, size=(12, 4))
print("Generated sales data (first 3 rows):\n", sales_data[:3])

Generated sales data (first 3 rows):
[[2732 4603 2711  166]
 [ 210 3906  937  927]
 [ 178 4356  776  553]]


In [4]:
# Creating a DataFrame with appropriate column and row labels
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
categories = ["Electronics", "Clothing", "Home & Kitchen", "Sports"]
df = pd.DataFrame(sales_data, columns=categories, index=months)
print("Monthly sales DataFrame:\n")
print(df)

Monthly sales DataFrame:
     Electronics  Clothing  Home & Kitchen  Sports
Jan         2732      4603            2711     166
Feb          210      3906             937     927
Mar          178      4356             776     553
Apr         2604      4973            4622    3155
May         4427      3701            2364    4847
Jun         3885      3619            1981    2832
Jul          823      3779             385    4773
Aug          763       282             370     420
Sep          796       262             420     250
Oct          221       724             145     660
Nov          324       836             768     813
Dec          175       180             181     181


Part-II

In [5]:
# Displaying the first few rows and summary statistics
print("Preview of the first 5 months:")
display(df.head())
print("\nStatistical summary:")
display(df.describe())